### PR TITLE
Enable scoped styles

### PR DESCRIPTION
**Pull request by d0cm0d**
Pass vue scope id to component parsing to allow scoped styles and call rewriteStyle() in processStyle() before minifying

### CODE REVIEW

**Comment by d0cm0d** [comment]
Hi,
I tried to get rid of the following test errors:
  ✖ renderer › String returns with zero config Error: render function or template not defined in component: foo
  ✖ renderer › String returns with some config Error: render function or template not defined in component: foo
  ✖ renderer › String returns with full object Error: render function or template not defined in component: foo
  ✖ renderer › String returns with no object Error: render function or template not defined in component: foo

Do you have an idea where the problem comes from? I tried to find it, but I am stuck ...

**Comment by d0cm0d** [comment]
I have fixed the issues now and added a little test case for the scoped styles

**Comment by danielcherubini** [comment]
looks good! 

thanks.. great first commit!

**Comment by danielcherubini** [comment]
ill get this in the next release tomorrow!

**Comment by d0cm0d** [comment]
Great 👍 Thank you very much for the fast answer!

**Comment by danielcherubini** [comment]
Done it's live in version  5.7.0

**Comment by danielcherubini** [comment]
Thankyou once again

**Comment by d0cm0d** [comment]
Thank you for the fast release! 👍

**Pull request merged**
