### PR TITLE
Load config from vueify to be able to override compilation options

### PR DESCRIPTION
**Pull request by Upd4ting**
I need that to be called to be able to override pug compilation option and set basedir to be able to use include/extends features from pug :)

### CODE REVIEW

**Comment by danielcherubini** [comment]
I'm so sorry i didn't see this sooner..

If there's no config .. will that call fail gracefully?

**Comment by Upd4ting** [comment]
Yeah sure if you check Vueify https://github.com/vuejs/vueify/blob/master/lib/compiler.js#L38
he first check that the config file exists

**Comment by danielcherubini** [comment]
Fantastic. I’ll get this merged in tomorrow morning. 

Sorry for the late reply.

**Comment by Upd4ting** [comment]
Amazing, thanks!

**Pull request merged**
