### PR TITLE
feat - add autoprefixer for postcss

### PR DESCRIPTION
**Pull request by dacsang97**
#71

### CODE REVIEW

**Comment by danielcherubini** [comment]
oh awesome thanks!

**Comment by danielcherubini** [comment]
i'll get this in soon

**Comment by dacsang97** [comment]
@danielcherubini how can I pass tslint + eslint :)), eslint no need trailing command, but tslint (run in travis) required it.

**Comment by danielcherubini** [comment]
shouldn't be any eslint left... its all tslint now...

hmm sorry for that if you had a problem

**Comment by dacsang97** [comment]
@danielcherubini no problem, I passed 👍

**Comment by dacsang97** [comment]
@danielcherubini can u review this PR for me soon? :D

**Pull request merged**
